name: Run Legitify

on:
  workflow_dispatch:

jobs:
  run_legitify:
    runs-on: ubuntu-latest
    steps:
      - uses: Legit-Labs/legitify@v1.0.3
        with: 
          github_token: ${{ secrets.LEGITIFY_GITHUB_PAT }} 
          analyze_self_only: true
          upload_code_scanning: true
